### ISSUE TITLE
[LandingPage] Remove colon after 3 boxes, update roadmap

### ISSUE THREAD

**Issue by NgocAnh7278** [aura-nw/landing-page#95]
- [ ] Remove colon after 3 boxes
![image](https://user-images.githubusercontent.com/40628286/160118950-9576624f-1274-4f3d-ad62-540223a5e822.png)

- [ ] Update "/" quater/year -> quater-year
![image](https://user-images.githubusercontent.com/40628286/160119125-0ec1a4c7-d333-4f0b-b242-8b6e23a0438c.png)
_Update_:
![image](https://user-images.githubusercontent.com/40628286/160119185-b1303a37-e76c-4b2a-bee8-35178b3b031b.png)

- [ ] Remove "." of Subtitle "Top-notch leaders and strategic insights"
![image](https://user-images.githubusercontent.com/72438169/160120954-60568762-2346-4aa5-aedb-05de0464fb80.png)

- [ ] Remove "." of Subtitle "A diversified team of blockchain believers"
![image](https://user-images.githubusercontent.com/72438169/160121226-aa60f1df-484e-43b9-8f8b-e93fe8a65149.png)

- [ ] Remove "." 
![image](https://user-images.githubusercontent.com/72438169/160121314-154fd681-5bf1-4790-8b30-842b8b6aa23f.png)
